name: Tests
on: [push]

jobs:
    phpunit:
        name: PHP ${{ matrix.php }} (${{ matrix.dependency-version }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [8.0, 8.1]
                dependency-version: [lowest, highest]
                exclude:
                    - php: 8.1
                      dependency-version: lowest
        steps:
            - uses: actions/checkout@v4

            - name: Configure PHP
              uses: shivammathur/setup-php@2.26.0
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependency-version }}
                  composer-options: "--no-suggest --prefer-dist"

            - name: Execute tests
              run: vendor/bin/phpunit
