name: Tests
on: [push]

jobs:
    phpunit:
        name: PHP ${{ matrix.php }} (${{ matrix.dependency-version }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [8.1, 8.2, 8.3]
                dependency-version: [lowest, highest]
        steps:
            - uses: actions/checkout@v4

            - name: Configure PHP
              uses: shivammathur/setup-php@2.31.1
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependency-version }}
                  composer-options: "--no-suggest --prefer-dist"

            - name: Execute tests
              run: vendor/bin/phpunit
